Demo_Login2/Models/Entities/AccountLopHoc.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Demo_Login2.Models.Entities
{
    public class AccountLopHoc
    {
        [Key]
        public int ID { get; set; }
        public int  Name { get; set; }
        public string Ma { get; set; }
        public int? IDLopHoc { get; set; }
        [ForeignKey("IDLopHoc")]
        public LopHoc LopHoc { get; set; }
        public int? IDAccount { get; set; }
        [ForeignKey("IDAccount")]
        public Account Account { get; set; }
        public bool IsDisabled { get; set; }
        public string GhiChu { get; set; }
  
    }
}

Demo_Login2/Areas/AdminPage/Controllers/AccountLopHocController.cs
using Demo_Login2.Areas.AdminPage.Business;
using Demo_Login2.Models.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Demo_Login2.Areas.AdminPage.Controllers
{
    public class AccountLopHocController : Controller
    {
        //Get: LayDanhSachChuNhiem
        public ActionResult Index()
        {
            var lstacclop = this.LayDanhSachAccountLopHocTheoKhoaDT(0);
            ViewBag.magiaovien = LayDanhSachTaiKhoan();
            ViewBag.tengiaovien = LayDanhSachTaiKhoan();
            ViewBag.phanloaitaikhoan = LayDanhSachTaiKhoan();
            ViewBag.phanloailophoc = LayDanhSachLopHoc();

            var listkhoaDT = LayDanhSachKhoaDaoTao();
            listkhoaDT.Insert(0, new KhoaDaoTaoDTO
            {
                ID = 0,
                TenKhoaDaoTao = "Tất cả Khóa Đào Tạo"
            });
            ViewData["khoaDT"] = new SelectList(listkhoaDT, "ID", "TenKhoaDaoTao",0);

            return View(lstacclop);
        }

        //Post :LayDanhSachChuNhiem
        [HttpPost]
        public ActionResult Index(int id)
        {
            var lstacclop = this.LayDanhSachAccountLopHocTheoKhoaDT(id);
            ViewBag.magiaovien = LayDanhSachTaiKhoan();
            ViewBag.tengiaovien = LayDanhSachTaiKhoan();
            ViewBag.phanloaitaikhoan = LayDanhSachTaiKhoan();
            ViewBag.phanloailophoc = LayDanhSachLopHoc();
            var listkhoaDT = this.LayDanhSachKhoaDaoTao();
            listkhoaDT.Insert(0, new KhoaDaoTaoDTO
            {
                ID = 0,
                TenKhoaDaoTao = "Tất cả Khóa Đào Tạo"
            });
            ViewData["khoaDT"] = new SelectList(listkhoaDT, "ID", "TenKhoaDaoTao",0);
            return View(lstacclop);
        }

        public List<KhoaDaoTaoDTO> LayDanhSachKhoaDaoTao()
        {
            using (KhoaDaoTaoBusiness bs = new KhoaDaoTaoBusiness())
            {
                return bs.LayDanhSachKhoaDaoTao();
            }
        }
        public List<AccountLopHocDTO> LayDanhSachAccountLopHocTheoKhoaDT(int id)
        {
            using (AccountLopHocBusiness bs = new AccountLopHocBusiness())
            {
                return bs.LayDanhSachAccountLopHocTheoKhoaDT(id);
            }
        }
        public List<AccountLopHocDTO> LayDanhSachAccountLopHoc()
        {
            using (AccountLopHocBusiness bs = new AccountLopHocBusiness())
            {
                return bs.LayDanhSachAccountLopHoc();
            }
        }

        public List<AccountDTO> LayDanhSachTaiKhoan_GiangVienDeChon(int id)
        {
            using (TaiKhoanBusiness bs = new TaiKhoanBusiness())
            {
                return bs.LayDanhSachTaiKhoan_GiangVienDeChon(id);
            }
        }

        public ActionResult Create_ThayDoiTaiKhoan(int id)
        {
            HttpCookie idAccount = HttpContext.Request.Cookies.Get("idAccount");
            HttpCookie idLopHoc = HttpContext.Request.Cookies.Get("idLopHoc");

            ViewData["magiaovien"] = new SelectList(LayDanhSachTaiKhoan_GiangVien(), "ID", "Ma", idAccount.Value);
            ViewData["tengiaovien"] = new SelectList(LayDanhSachTaiKhoan_GiangVienDeChon(id), "ID", "HoVaTen");
            ViewData["account"] = new SelectList(LayDanhSachTaiKhoan_GiangVienDeChon(id), "ID", "MailVL");
            ViewData["lophoc"] = new SelectList(LayDanhSachLopHoc(), "ID", "TenLop", idLopHoc.Value);
            return View("Create");

        }

        //Get : TaoChuNhiem
        public ActionResult Create()
        {
            var lstAccount = LayDanhSachTaiKhoan_GiangVien();

            ViewData["magiaovien"] = new SelectList(LayDanhSachTaiKhoan_GiangVien(), "ID", "Ma");
            ViewData["tengiaovien"] = new SelectList(LayDanhSachTaiKhoan_GiangVienDeChon(lstAccount[0].ID), "ID", "HoVaTen");
            ViewData["account"] = new SelectList(LayDanhSachTaiKhoan_GiangVienDeChon(lstAccount[0].ID), "ID", "MailVL");
            ViewData["lophoc"] = new SelectList(LayDanhSachLopHoc(), "ID", "TenLop");
            return View();
        }
        //Post :TaoChuNhiem
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AccountLopHocDTO acclop)
        {


            var findlop = LayLopHocDaTonTai(acclop.IDLopHoc);
            var findgv = LayGiangVienDaTonTai(acclop.IDAccount);
            Response.Cookies.Remove("idAccount");
            Response.Cookies.Remove("idLopHoc");

            if (findgv > 0)
            {
                ViewBag.Errorgv = "Giảng viên đã là chủ nhiệm lớp khác";
                ViewData["magiaovien"] = new SelectList(LayDanhSachTaiKhoan_GiangVien(), "ID", "Ma");
                ViewData["tengiaovien"] = new SelectList(LayDanhSachTaiKhoan_GiangVienDeChon(Convert.ToInt32(acclop.IDAccount)), "ID", "HoVaTen");
                ViewData["account"] = new SelectList(LayDanhSachTaiKhoan_GiangVienDeChon(Convert.ToInt32(acclop.IDAccount)), "ID", "MailVL");
                ViewData["lophoc"] = new SelectList(LayDanhSachLopHoc(), "ID", "TenLop");
                return View();
            }
            else if (findlop > 0)
            {
                ViewBag.Errorlop = "Lớp đã có chủ nhiệm";
                ViewData["magiaovien"] = new SelectList(LayDanhSachTaiKhoan_GiangVien(), "ID", "Ma");
                ViewData["tengiaovien"] = new SelectList(LayDanhSachTaiKhoan_GiangVienDeChon(Convert.ToInt32(acclop.IDAccount)), "ID", "HoVaTen");
                ViewData["account"] = new SelectList(LayDanhSachTaiKhoan_GiangVienDeChon(Convert.ToInt32(acclop.IDAccount)), "ID", "MailVL");
                ViewData["lophoc"] = new SelectList(LayDanhSachLopHoc(), "ID", "TenLop");
                return View();
            }
            else
            {
                ThemAccountLopHoc(acclop);
                TempData["Success"] = "Thành công";
                return RedirectToAction("Index");
            }

        }

        //Upload Danh sach Excel 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Upload(FormCollection formCollection)
        {
            if (Request != null)
            {
                HttpPostedFileBase file = Request.Files["UploadedFile"];
                if ((file != null) && (file.ContentLength > 0) && !string.IsNullOrEmpty(file.FileName))
                {
                    OfficeOpenXml.ExcelPackage.LicenseContext = OfficeOpenXml.LicenseContext.NonCommercial;
                    using (var package = new OfficeOpenXml.ExcelPackage(file.InputStream))
                    {
                        var currentSheet = package.Workbook.Worksheets;
                        var workSheet = currentSheet.First();
                        var noOfCol = workSheet.Dimension.End.Column;
                        var noOfRow = workSheet.Dimension.End.Row;
                        ViewBag.Error = "";
                        List<AccountLopHocDTO> accountlophocList = new List<AccountLopHocDTO>();

                        List<int> lstRowCheck_TaiKhoan_TonTai = new List<int>();
                        List<int> lstRowCheck_LopHoc_TonTai = new List<int>();
                        List<int> lstRowCheck_TaiKhoan_Trong = new List<int>();
                        List<int> lstRowCheck_LopHoc_Trong = new List<int>();
                        List<int> lstRowError_MaTaiKhoan_BiTrungTrenFileExcel = new List<int>();
                        //List<int> lstRowError_Mail_DinhDangHopLe = new List<int>();

                        for (int rowIterator = 2; rowIterator <= noOfRow; rowIterator++)
                        {
                            try
                            {
                                var lstchunhiem = new AccountLopHocDTO();
                                var magiangvien = Convert.ToString(workSheet.Cells[rowIterator, 1].Value).Trim();
                                var lophoc = Convert.ToString(workSheet.Cells[rowIterator, 2].Value).Trim();
                                var ghichu = Convert.ToString(workSheet.Cells[rowIterator, 3].Value).Trim();

                                var IDAccount = LayIDAccountTheoMa(magiangvien);
                                var IDLopHoc = LayIDLopHocTheoTen(lophoc);
                                var check_taikhoantontai = Check_TaiKhoanTonTai(IDAccount);
                                var check_tenloptontai = Check_LopHocTonTai(IDLopHoc);

                               
                                //var checkMail = LayMailHopLe(acc.MailVL);

                                if (IDAccount == 0)
                                {
                                    lstRowCheck_TaiKhoan_Trong.Add(rowIterator);
                                }                               
                                if(IDLopHoc == 0)
                                {
                                    lstRowCheck_LopHoc_Trong.Add(rowIterator);
                                }
                                if (check_taikhoantontai > 0)
                                {
                                    lstRowCheck_TaiKhoan_TonTai.Add(rowIterator);
                                }
                                if (check_tenloptontai > 0)
                                {
                                    lstRowCheck_LopHoc_TonTai.Add(rowIterator);
                                }
                                //if (checkMail == false)
                                //{

                                //    lstRowError_Mail_DinhDangHopLe.Add(rowIterator);
                                //}
                                else
                                {
                                    var checkloimataikhoantrungtrenExcel = accountlophocList.Where(s => s.IDAccount == IDAccount).FirstOrDefault();
                                    if (checkloimataikhoantrungtrenExcel != null)
                                    {

Demo_Login2/Areas/AdminPage/Views/AccountLopHoc/Create.cshtml
@model Demo_Login2.Models.DTO.AccountLopHocDTO
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Chủ Nhiệm</h1>
                    <br />
                    <button class="btn btn-outline-warning" onclick="location.href='@Url.Action("Index", "AccountLopHoc")'">
                        <i class="fas fa-arrow-left"></i>
                        Quay về
                    </button>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Thêm Chủ Nhiệm</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        @using (Html.BeginForm("Create", "AccountLopHoc"))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Ma, "Mã Giáo Viên", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.Ma, @ViewData["magiaovien"] as SelectList, htmlAttributes: new { @class = "form-control", @id = "idAccount" })
                        @Html.ValidationMessageFor(model => model.Ma, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, "Tên Giáo Viên", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.IDAccount, @ViewData["tengiaovien"] as SelectList, htmlAttributes: new { @class = "form-control"})
                        @Html.ValidationMessageFor(model => model.IDAccount, "", new { @class = "text-danger" })
                    </div>
                </div>
                <p class="text-danger">@ViewBag.Errorgv</p>
                <div class="form-group">
                    @Html.LabelFor(model => model.IDAccount, "Tài khoản giáo viên", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @*@Html.EditorFor(model => model.IDAccount, new { htmlAttributes = new { @class = "form-control" } })*@

                        @Html.DropDownListFor(model => model.IDAccount, @ViewData["account"] as SelectList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IDAccount, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.IDLopHoc, "Lớp chủ nhiệm", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.IDLopHoc, @ViewData["lophoc"] as SelectList, htmlAttributes: new { @class = "form-control", @id = "idLopHoc" })
                        @Html.ValidationMessageFor(model => model.IDLopHoc, "", new { @class = "text-danger" })
                    </div>
                </div>
                <p class="text-danger">@ViewBag.Errorlop</p>
                @*<div class="form-group">
                        @Html.LabelFor(model => model.IsDisable, "Check", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.IsDisable, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.IsDisable, "", new { @class = "text-danger" })
                        </div>
                    </div>*@
                <div class="form-group">
                    @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.GhiChu, new { cols = 60, rows = 10, @class = "form-control", placeholder = "Nhập Ghi Chú" })
                        @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @*<input type="submit" value="Lưu" class="btn btn-default" />*@
                    <button class="btn btn-outline-success">
                        <i class="fas fa-check"></i>
                        Lưu
                    </button>
                </div>
            </div>
        }

    </section>
    <div class="col-md-offset-2 col-md-3">

    </div>
</div>

<script src="~/Content/plugins/jquery/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#idAccount").change(function () {
            var idAccount = $('#idAccount').val();
            var idLopHoc = $('#idLopHoc').val();

            document.cookie = "idAccount=" + idAccount;
            document.cookie = "idLopHoc=" + idLopHoc;

            var link = '@Url.Action("Create_ThayDoiTaiKhoan", "AccountLopHoc", new { id = "_id_" })';
            link = link.replace("_id_", idAccount);
            location.pathname = link;
        });
    })
</script>

Demo_Login2/Areas/AdminPage/Views/AccountLopHoc/Details.cshtml
@model Demo_Login2.Models.DTO.AccountLopHocDTO
@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Chi Tiết Chủ Nhiệm</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                            <li class="breadcrumb-item active">Chi tiết Chủ Nhiệm</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <section class="content">
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.IDAccount, "Mã giáo viên", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @foreach (var row in ViewBag.magiaovien)
                        {
                            if (row.ID == Model.IDAccount)
                            {
                                <p>@row.Ma</p>
                            }
                        }
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.IDAccount, "Tên giáo viên", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @foreach (var row in ViewBag.tengiaovien)
                        {
                            if (row.ID == Model.IDAccount)
                            {
                                <p>@row.HoVaTen</p>
                            }
                        }
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IDAccount, "Tài khoản giáo viên", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @foreach (var row in ViewBag.taikhoan)
                        {
                            if (row.ID == Model.IDAccount)
                            {
                                <p>@row.MailVL</p>
                            }
                        }
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.IDLopHoc, "Lớp chủ nhiệm", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @foreach (var row in ViewBag.lophoc)
                        {
                            if (row.ID == Model.IDLopHoc)
                            {
                                <p>@row.TenLop</p>
                            }
                        }
                    </div>
                </div>
                @*<div class="form-group">
            @Html.LabelFor(model => model.IsDisable, "Check", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.IsDisable, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>*@

                <div class="form-group">
                    @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DisplayFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })

                    </div>
                </div>
            </div>
        </section>
        <br />
        <button class="btn btn-outline-warning" onclick="location.href='@Url.Action("Index", "AccountLopHoc")'">
            <i class="fas fa-arrow-left"></i>
            Quay về
        </button>
    </div>

Demo_Login2/Areas/AdminPage/Views/AccountLopHoc/Edit.cshtml
@model Demo_Login2.Models.DTO.AccountLopHocDTO
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Chủ Nhiệm</h1>
                    <br />
                    <button class="btn btn-outline-warning" onclick="location.href='@Url.Action("Index", "AccountLopHoc")'">
                        <i class="fas fa-arrow-left"></i>
                        Quay về
                    </button>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Sửa chủ nhiệm</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        @using (Html.BeginForm("Edit", "AccountLopHoc", new { @id = Request.Cookies["idEdit"].Value }))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <hr />
                @Html.HiddenFor(model => model.ID)
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.IDAccount, "Mã Giảng Viên", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.IDAccount, @ViewData["magiaovien"] as SelectList, htmlAttributes: new { @class = "form-control", @id = "idAccount" })
                        @Html.ValidationMessageFor(model => model.IDAccount, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, "Tên Giáo Viên", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.IDAccount, @ViewData["tengiaovien"] as SelectList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IDAccount, "", new { @class = "text-danger" })
                    </div>
                </div>
                <p class="text-danger">@ViewBag.Errorgv</p>
                <div class="form-group">
                    @Html.LabelFor(model => model.IDAccount, "Tài khoản giáo viên", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.IDAccount, @ViewData["account"] as SelectList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IDAccount, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.IDLopHoc, "Lớp chủ nhiệm", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.IDLopHoc, @ViewData["lophoc"] as SelectList, htmlAttributes: new { @class = "form-control", @id = "idLopHoc" })
                        @Html.ValidationMessageFor(model => model.IDLopHoc, "", new { @class = "text-danger" })
                    </div>
                </div>
                <p class="text-danger">@ViewBag.Errorlop</p>
                @*<div class="form-group">
                        @Html.LabelFor(model => model.IsDisable, "Check", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.IsDisable, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.IsDisable, "", new { @class = "text-danger" })
                        </div>
                    </div>*@
                <div class="form-group">
                    @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.GhiChu, new { cols = 60, rows = 10, @class = "form-control", placeholder = "Nhập Ghi Chú" })
                        @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <button class="btn btn-outline-success">
                    <i class="fas fa-check"></i>
                    Lưu
                </button>
            </div>
        }
    </section>
</div>

<script src="~/Content/plugins/jquery/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#idAccount").change(function () {
            var idAccount = $('#idAccount').val();
            var idLopHoc = $('#idLopHoc').val();

            document.cookie = "idAccount=" + idAccount;
            document.cookie = "idLopHoc=" + idLopHoc;

            var link = '@Url.Action("Edit_ThayDoiTaiKhoan", "AccountLopHoc", new { id = "_id_" })';
            link = link.replace("_id_", idAccount);
            location.pathname = link;
        });
    })
</script>