Demo_Login2/Models/Entities/TrangThaiDangKiMonHoc.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Demo_Login2.Models.Entities
{
    public class TrangThaiDangKiMonHoc
    {
        [Key]
        public int ID { get; set; }
        public int? IDKhoaDaoTao { get; set; }
        [ForeignKey("IDKhoaDaoTao")]
        public KhoaDaoTao KhoaDaoTao { get; set; }
        public int? IDHocKi { get; set; }
        [ForeignKey("IDHocKi")]
        public HocKi HocKi { get; set; }
        public string ThoiGianBatDau { get; set; }
        public string ThoiGianKetThuc { get; set; }
        public bool TrangThai { get; set; }
        public string GhiChu { get; set; }

    }
}

Demo_Login2/Areas/AdminPage/Controllers/TrangThaiDangKiMonHocController.cs
using Demo_Login2.Areas.AdminPage.Business;
using Demo_Login2.Models.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Demo_Login2.Areas.AdminPage.Controllers
{
    public class TrangThaiDangKiMonHocController : Controller
    {
        // GET: AdminPage/TrangThaiDangKiMonHoc
        public ActionResult Index()
        {
            var lsttrangthai = LayDanhSachTrangThaiDangKiMonHoc();
            ViewBag.khoaDT = LayDanhSachKhoaDaoTao();
            ViewBag.hocki = LayDanhSachHocKi();
            foreach(var item in lsttrangthai)
            {
                Mo_TrangThaiDangKiMonHoc(Convert.ToInt32(item.IDKhoaDaoTao), Convert.ToInt32(item.IDHocKi));
            }
            foreach(var item1 in lsttrangthai)
            {
                Check_TrangThaiMonHocQuaThoiGianDangKi(Convert.ToInt32(item1.IDKhoaDaoTao), Convert.ToInt32(item1.IDHocKi));
            }
            return View(lsttrangthai);
        }

        public bool Mo_TrangThaiDangKiMonHoc(int idKhoaDT,int idHocKi)
        {
            using (TrangThaiDangKiMonHocBusiness bs = new TrangThaiDangKiMonHocBusiness())
            {
                return bs.Mo_TrangThaiDangKiMonHoc(idKhoaDT,idHocKi);
            }
        }

        public bool Check_TrangThaiMonHocQuaThoiGianDangKi(int idKhoaDT, int idHocKi)
        {
            using (TrangThaiDangKiMonHocBusiness bs = new TrangThaiDangKiMonHocBusiness())
            {
                return bs.Check_TrangThaiMonHocQuaThoiGianDangKi(idKhoaDT, idHocKi);
            }
        }

        public List<HocKiDTO> LayDanhSachHocKi()
        {
            using(HocKiBusiness bs = new HocKiBusiness())
            {
                return bs.LayDanhSachHocKi();
            }
        }

        public List<TrangThaiDangKiMonHocDTO> LayDanhSachTrangThaiDangKiMonHoc()
        {
            using(TrangThaiDangKiMonHocBusiness bs = new TrangThaiDangKiMonHocBusiness())
            {
                return bs.LayDanhSachTrangThaiDangKiMonHoc();
            }
        }

        public List<KhoaDaoTaoDTO> LayDanhSachKhoaDaoTao()
        {
            using(KhoaDaoTaoBusiness bs = new KhoaDaoTaoBusiness())
            {
                return bs.LayDanhSachKhoaDaoTao();
            }
        }

        //Get : TaoTrangThaiDangKiMonHoc
        public ActionResult Create()
        {
            ViewData["khoaDT"] = new SelectList(LayDanhSachKhoaDaoTao(), "ID", "TenKhoaDaoTao");
            ViewData["hocki"] = new SelectList(LayDanhSachHocKi(), "ID", "TenHocKi");
            return View();
        }
        //Post : TaoTrangThaiDangKiMonHoc
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(TrangThaiDangKiMonHocDTO trangthaidangki)
        {
            var id = LayHocKiTheoKhoaDaoTaoDaTonTai(trangthaidangki.IDHocKi,trangthaidangki.IDKhoaDaoTao);
            var sosanh = SoSanhThoiGian(trangthaidangki.ThoiGianBatDau, trangthaidangki.ThoiGianKetThuc);

            //so sanh thoi gian mo mon hoc
            var thoigianbatdau = Convert.ToDateTime(trangthaidangki.ThoiGianBatDau);
            var thoigianketthuc = Convert.ToDateTime(trangthaidangki.ThoiGianKetThuc);
            var thoigianhientai = DateTime.Now;

            if(thoigianbatdau <= thoigianhientai && thoigianhientai <= thoigianketthuc)
            {
                trangthaidangki.TrangThai = true;
            }
            else
            {
                trangthaidangki.TrangThai = false;
            }
            //bat loi mo dang ki mon hoc
            if (trangthaidangki.ThoiGianBatDau == null || trangthaidangki.ThoiGianKetThuc == null)
            {
                ViewBag.Errorkhongnhapthoigian = "Thời gian bắt đầu hoặc kết thúc không được để trống";
                ViewData["khoaDT"] = new SelectList(LayDanhSachKhoaDaoTao(), "ID", "TenKhoaDaoTao");
                ViewData["hocki"] = new SelectList(LayDanhSachHocKi(), "ID", "TenHocKi");
                return View();
            }
            else if (id > 0)
            {
                ViewBag.Error = "Học Kì trong Khóa Đào Tạo này đã tồn tại";
                ViewData["khoaDT"] = new SelectList(LayDanhSachKhoaDaoTao(), "ID", "TenKhoaDaoTao");
                ViewData["hocki"] = new SelectList(LayDanhSachHocKi(), "ID", "TenHocKi");
                return View();
            } else if (sosanh == false)
            {
                ViewBag.ErrorThoiGian = "Thời gian kết thúc phải sau hoặc không trùng Thời gian bắt đầu";
                ViewData["khoaDT"] = new SelectList(LayDanhSachKhoaDaoTao(), "ID", "TenKhoaDaoTao");
                ViewData["hocki"] = new SelectList(LayDanhSachHocKi(), "ID", "TenHocKi");
                return View();
            }            
            else
            {
                ThemTrangThaiDangKiMonHoc(trangthaidangki);
                TempData["Success"] = "Thành công";
                return RedirectToAction("Index");
            }


        }

        public int LayHocKiTheoKhoaDaoTaoDaTonTai(int? idHocKi,int? idKhoaDaoTao)
        {
            using (KhoaDaoTaoBusiness bs = new KhoaDaoTaoBusiness())
            {
                return bs.LayHocKiTheoKhoaDaoTaoDaTonTai(idHocKi,idKhoaDaoTao);
            }
        }
        public bool SoSanhThoiGian(string startDate, string endDate)
        {
            var ngaybatdau = Convert.ToDateTime(startDate);
            var ngayketthuc = Convert.ToDateTime(endDate);
            if(ngayketthuc <= ngaybatdau)
            {
                return false;
            }
            return true;

        }
        public bool ThemTrangThaiDangKiMonHoc(TrangThaiDangKiMonHocDTO trangthai)
        {
            using(TrangThaiDangKiMonHocBusiness bs = new TrangThaiDangKiMonHocBusiness())
            {
                return bs.ThemTrangThaiDangKiMonHoc(trangthai);
            }
        }

        //Get : SuaTrangThaiDangKiMonHoc
        public ActionResult Edit(int id)
        {
            TrangThaiDangKiMonHocDTO trangthai = LayTrangThaiDangKiMonHoc(id);
            ViewData["khoaDT"] = new SelectList(LayDanhSachKhoaDaoTao(), "ID", "TenKhoaDaoTao");
            ViewData["hocki"] = new SelectList(LayDanhSachHocKi(), "ID", "TenHocKi");
            return View(trangthai);
        }

        //Post : SuaTrangThaiDangKiMonHoc
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(TrangThaiDangKiMonHocDTO trangthaidangki)
        {
            var findkhoa = LayHocKiTheoKhoaDaoTaoDaTonTai(trangthaidangki.IDHocKi,trangthaidangki.IDKhoaDaoTao);
            var sosanh = SoSanhThoiGian(trangthaidangki.ThoiGianBatDau, trangthaidangki.ThoiGianKetThuc);

            //so sanh thoi gian mo mon hoc
            var thoigianbatdau = Convert.ToDateTime(trangthaidangki.ThoiGianBatDau);
            var thoigianketthuc = Convert.ToDateTime(trangthaidangki.ThoiGianKetThuc);
            var thoigianhientai = DateTime.Now;

            if(thoigianbatdau <= thoigianhientai && thoigianhientai <= thoigianketthuc)
            {
                trangthaidangki.TrangThai = true;
            }
            else
            {
                trangthaidangki.TrangThai = false;
            }

            //bat loi mo dang ki mon hoc
            if ((findkhoa == trangthaidangki.ID || findkhoa == 0) && sosanh == true && (trangthaidangki.ThoiGianBatDau != null && trangthaidangki.ThoiGianKetThuc != null))
            {
                SuaTrangThaiDangKiMonHoc(trangthaidangki);
                TempData["Success"] = "Thành công";
                return RedirectToAction("Index");
            }
            else
            {
                if (findkhoa != trangthaidangki.ID && findkhoa > 0)
                {
                    ViewBag.Error = "Học Kì trong Khóa Đào Tạo này đã tồn tại";
                    ViewData["khoaDT"] = new SelectList(LayDanhSachKhoaDaoTao(), "ID", "TenKhoaDaoTao");
                    ViewData["hocki"] = new SelectList(LayDanhSachHocKi(), "ID", "TenHocKi");
                    return View();

                }
                else if (trangthaidangki.ThoiGianBatDau == null || trangthaidangki.ThoiGianKetThuc == null)
                {
                    ViewBag.Errorkhongnhapthoigian = "Thời gian bắt đầu hoặc kết thúc không được để trống";
                    ViewData["khoaDT"] = new SelectList(LayDanhSachKhoaDaoTao(), "ID", "TenKhoaDaoTao");
                    ViewData["hocki"] = new SelectList(LayDanhSachHocKi(), "ID", "TenHocKi");
                    return View();
                }
                else if(sosanh == false)
                {
                    ViewBag.ErrorThoiGian = "Thời gian kết thúc phải sau hoặc không trùng Thời gian bắt đầu";
                    ViewData["khoaDT"] = new SelectList(LayDanhSachKhoaDaoTao(), "ID", "TenKhoaDaoTao");
                    ViewData["hocki"] = new SelectList(LayDanhSachHocKi(), "ID", "TenHocKi");
                    return View();
                }
                else
                {
                    return View();
                }
            }

        }

        public TrangThaiDangKiMonHocDTO LayTrangThaiDangKiMonHoc(int id)
        {
            using (TrangThaiDangKiMonHocBusiness bs = new TrangThaiDangKiMonHocBusiness())
            {
                return bs.LayTrangThaiDangKiMonHoc(id);
            }
        }

        public bool SuaTrangThaiDangKiMonHoc(TrangThaiDangKiMonHocDTO trangthai)
        {
            using(TrangThaiDangKiMonHocBusiness bs = new TrangThaiDangKiMonHocBusiness())
            {
                return bs.SuaTrangThaiDangKiMonHoc(trangthai);
            }
        }

        //XoaTrangThaiDangKiMonHoc
        public async Task<ActionResult> Delete(int id)
        {
            var output = XoaTrangThaiDangKiMonHoc(id);
            if (output)
            {
                TempData["Success"] = "Thành công";
                return RedirectToAction("Index");

Demo_Login2/Areas/AdminPage/Views/TrangThaiDangKiMonHoc/Create.cshtml
@model Demo_Login2.Models.DTO.TrangThaiDangKiMonHocDTO
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Thêm Mở Trạng Thái Đăng Kí Môn Học</h1>
                    <br />
                    <button class="btn btn-outline-warning" onclick="location.href='@Url.Action("Index", "TrangThaiDangKiMonHoc")'">
                        <i class="fas fa-arrow-left"></i>
                        Quay về
                    </button>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Thêm Mở Trạng Thái Đăng Kí Môn Học</li>
                    </ol>

                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.IDKhoaDaoTao, "Khóa đào tạo", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.IDKhoaDaoTao, @ViewData["khoaDT"] as SelectList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IDKhoaDaoTao, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.IDHocKi, "Học Kì", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.IDHocKi, @ViewData["hocki"] as SelectList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IDHocKi, "", new { @class = "text-danger" })
                    </div>
                </div>
                <p class="text-danger">@ViewBag.Error</p>
                <div class="form-group">
                    @Html.LabelFor(model => model.ThoiGianBatDau, "Thời gian bắt đầu", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.ThoiGianBatDau, new { @type = "datetime-local", @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ThoiGianBatDau, "", new { @class = "text-danger" })
                    </div>
                </div>
                <p class="text-danger">@ViewBag.Errorkhongnhapthoigian</p>

                <div class="form-group">
                    @Html.LabelFor(model => model.ThoiGianKetThuc, "Thời gian kết thúc", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.ThoiGianKetThuc, new { @type = "datetime-local", @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ThoiGianKetThuc, "", new { @class = "text-danger" })
                    </div>
                </div>
                <p class="text-danger">@ViewBag.ErrorThoiGian</p>
                <p class="text-danger">@ViewBag.Errorkhongnhapthoigian</p>
                @*<div class="form-group">
                        @Html.LabelFor(model => model.TrangThai, "Trạng thái", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="form-group row">
                                <div class="col-sm-2" style="margin: 0 auto; min-width: 478px; display: flex; justify-content: center; align-items: center;text-align:center;right: -4px; ">
                                    <label style="margin-right: 15px; margin-bottom: 0; font-size: 19px; min-width: 200px;  ">Mở</label>
                                </div>
                            </div>
                            @Html.EditorFor(model => model.TrangThai, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
                        </div>
                    </div>*@
                <div class="form-group">
                    @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.GhiChu, new { cols = 60, rows = 10, @class = "form-control", placeholder = "Nhập Ghi Chú" })
                        @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button class="btn btn-outline-success">
                        <i class="fas fa-check"></i>
                        Lưu
                    </button>
                </div>
            </div>
        }
    </section>
</div>

<script>
    function goBack() {
        window.history.back();
    }
</script>

Demo_Login2/Areas/AdminPage/Views/TrangThaiDangKiMonHoc/Details.cshtml
@model Demo_Login2.Models.DTO.TrangThaiDangKiMonHocDTO
@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Chi Tiết Trạng Thái Đăng Kí Môn Học</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Chi Tiết Trạng Thái Đăng Kí Môn Học</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.IDKhoaDaoTao, "Khóa Đào Tạo", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @foreach (var row in ViewBag.khoaDT)
                    {
                        if (row.ID == Model.IDKhoaDaoTao)
                        {
                            <p>@row.TenKhoaDaoTao</p>
                        }
                    }
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.IDHocKi, "Học Kì", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @foreach (var row in ViewBag.hocki)
                    {
                        if (row.ID == Model.IDHocKi)
                        {
                            <p>@row.TenHocKi</p>
                        }
                    }
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ThoiGianBatDau, "Thời gian bắt đầu", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.ThoiGianBatDau, new { @type = "datetime-local", @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ThoiGianBatDau, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.ThoiGianKetThuc, "Thời gian kết thúc", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.ThoiGianKetThuc, new { @type = "datetime-local", @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ThoiGianKetThuc, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.TrangThai, "Trạng thái", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.TrangThai, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })

                </div>
            </div>
        </div>
    </section>
    <br />
    <button class="btn btn-outline-warning" onclick="location.href='@Url.Action("Index", "TrangThaiDangKiMonHoc")'">
        <i class="fas fa-arrow-left"></i>
        Quay về
    </button>
</div>

Demo_Login2/Areas/AdminPage/Views/TrangThaiDangKiMonHoc/Edit.cshtml
@model Demo_Login2.Models.DTO.TrangThaiDangKiMonHocDTO
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Sửa Mở Trạng Thái Đăng Kí Môn Học</h1>
                    <br />
                    <button class="btn btn-outline-warning" onclick="location.href='@Url.Action("Index", "TrangThaiDangKiMonHoc")'">
                        <i class="fas fa-arrow-left"></i>
                        Quay về
                    </button>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Sửa Mở Trạng Thái Đăng Kí Môn Học</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.IDKhoaDaoTao, "Khóa đào tạo", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.IDKhoaDaoTao, @ViewData["khoaDT"] as SelectList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IDKhoaDaoTao, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.IDHocKi, "Học Kì", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.IDHocKi, @ViewData["hocki"] as SelectList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IDHocKi, "", new { @class = "text-danger" })
                    </div>
                </div>
                <p class="text-danger">@ViewBag.Error</p>
                <div class="form-group">
                    @Html.LabelFor(model => model.ThoiGianBatDau, "Thời gian bắt đầu", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.ThoiGianBatDau, new { @type = "datetime-local", @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ThoiGianBatDau, "", new { @class = "text-danger" })
                    </div>
                </div>
                <p class="text-danger">@ViewBag.Errorkhongnhapthoigian</p>

                <div class="form-group">
                    @Html.LabelFor(model => model.ThoiGianKetThuc, "Thời gian kết thúc", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.ThoiGianKetThuc, new { @type = "datetime-local", @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ThoiGianKetThuc, "", new { @class = "text-danger" })
                    </div>
                </div>
                <p class="text-danger">@ViewBag.ErrorThoiGian</p>
                <p class="text-danger">@ViewBag.Errorkhongnhapthoigian</p>
                @*<div class="form-group">
                        @Html.LabelFor(model => model.TrangThai, "Trạng thái", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="form-group row">
                                <div class="col-sm-2" style="margin: 0 auto; min-width: 478px; display: flex; justify-content: center; align-items: center;text-align:center;right: -4px; ">
                                    <label style="margin-right: 15px; margin-bottom: 0; font-size: 19px; min-width: 200px;  ">Mở</label>
                                </div>
                            </div>
                            @Html.EditorFor(model => model.TrangThai, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
                        </div>
                    </div>*@
                <div class="form-group">
                    @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.GhiChu, new { cols = 60, rows = 10, @class = "form-control", placeholder = "Nhập Ghi Chú" })
                        @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button class="btn btn-outline-success">
                        <i class="fas fa-check"></i>
                        Lưu
                    </button>
                </div>
            </div>
        }
    </section>
</div>

<script>
    function goBack() {
        window.history.back();
    }
</script>