Demo_Login2/Models/Entities/HocPhanTienQuyet.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Demo_Login2.Models.Entities
{
    public class HocPhanTienQuyet
    {
        [Key]
        public int ID { get; set; }
        public int? IDMonHoc { get; set; }
        [ForeignKey("IDMonHoc")]
        public MonHoc MonHoc { get; set; }
        public int? IDMonHocTienQuyet { get; set; }
        [ForeignKey("IDMonHocTienQuyet")]
        public MonHoc MonHocTienQuyet { get; set; }
        public string GhiChu { get; set; }
        //public ICollection<MonHoc> MonHocs_IDHocPhanTienQuyet { get; set; }
        public ICollection<MonHocKhoaDaoTao> MonHocKhoaDaoTaos_IDHocPhanTienQuyet { get; set; }
        public ICollection<MonHocSinhVienDangKi> MonHocSinhVienDangKis_IDHocPhanTienQuyet { get; set; }
        public ICollection<KetQuaHocTap> KetQuaHocTaps_IDHocPhanTienQuyet { get; set; }
        
    }
}

Demo_Login2/Areas/AdminPage/Controllers/HocPhanTienQuyetController.cs
using Demo_Login2.Areas.AdminPage.Business;
using Demo_Login2.Models.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Demo_Login2.Areas.AdminPage.Controllers
{
    public class HocPhanTienQuyetController : Controller
    {
        //LayDanhSachHocPhanTienQuyet
        public ActionResult Index()
        {
            var lsthocphanTQ = LayDanhSachHocPhanTienQuyet();
            ViewBag.monhoc = LayDanhSachMonHoc();
            ViewBag.monhoctienquyet = LayDanhSachMonHoc();
            return View(lsthocphanTQ);
        }
        public List<MonHocDTO> LayDanhSachMonHoc()
        {
            using (MonHocBusiness bs = new MonHocBusiness())
            {
                return bs.LayDanhSachMonHoc();
            }
        }
 
        public List<HocPhanTienQuyetDTO> LayDanhSachHocPhanTienQuyet()
        {
            using(HocPhanTienQuyetBusiness bs = new HocPhanTienQuyetBusiness())
            {
                return bs.LayDanhSachHocPhanTienQuyet();
            }
        }
        public ActionResult Create_ThayDoiMonHoc(int id)
        {
            HttpCookie idMonHoc = HttpContext.Request.Cookies.Get("idMonHoc");
            ViewData["monhoc"] = new SelectList(LayDanhSachMonHoc(), "ID", "TenMonHoc", idMonHoc.Value);
            ViewData["monhoctienquyet"] = new SelectList(LayDanhSachMonHocTienQuyet(id), "ID", "TenMonHoc");
            return View("Create");
        }

        //Get : TaoHocPhanTienQuyet
        public ActionResult Create()
        {
            var lstmonhoc = LayDanhSachMonHoc();
            ViewData["monhoc"] = new SelectList(LayDanhSachMonHoc(), "ID", "TenMonHoc");
            ViewData["monhoctienquyet"] = new SelectList(LayDanhSachMonHocTienQuyet(lstmonhoc[0].ID), "ID", "TenMonHoc");
            return View();
        }

        //Post : TaoHocPhanTienQuyet
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(HocPhanTienQuyetDTO hocphanTQ)
        {
            var findmonhoc = CheckLoiMonHocTienQuyetTheoMonHocDaTonTai(hocphanTQ.IDMonHoc, hocphanTQ.IDMonHocTienQuyet);
            Response.Cookies.Remove("idMonHoc");
            if (findmonhoc > 0)
            {
                ViewBag.Error = "Môn Học Tiên Quyết đã trong Môn Học này";
                var lstmonhoc = LayDanhSachMonHoc();
                ViewData["monhoc"] = new SelectList(LayDanhSachMonHoc(), "ID", "TenMonHoc");
                ViewData["monhoctienquyet"] = new SelectList(LayDanhSachMonHocTienQuyet(Convert.ToInt32(hocphanTQ.IDMonHoc)), "ID", "TenMonHoc");
                return View();
            }
            else
            {
                ThemHocPhanTienQuyet(hocphanTQ);
                return RedirectToAction("Index");
            }
            //var output = ThemHocPhanTienQuyet(hocphanTQ);
            //Response.Cookies.Remove("idMonHoc");
            //if (output)
            //{
            //    return RedirectToAction("Index");
            //}
            //else
            //{
            //    return View("Fail");
            //}


        }

        //Upload Danh sach Excel 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Upload(FormCollection formCollection)
        {
            if (Request != null)
            {
                HttpPostedFileBase file = Request.Files["UploadedFile"];
                if ((file != null) && (file.ContentLength > 0) && !string.IsNullOrEmpty(file.FileName))
                {
                    OfficeOpenXml.ExcelPackage.LicenseContext = OfficeOpenXml.LicenseContext.NonCommercial;
                    using (var package = new OfficeOpenXml.ExcelPackage(file.InputStream))
                    {
                        var currentSheet = package.Workbook.Worksheets;
                        var workSheet = currentSheet.First();
                        var noOfCol = workSheet.Dimension.End.Column;
                        var noOfRow = workSheet.Dimension.End.Row;
                        ViewBag.Error = "";
                        List<HocPhanTienQuyetDTO> hocphantienquyetList = new List<HocPhanTienQuyetDTO>();

                        List<int> lstRowError_TenMonHocTienQuyet_Trung = new List<int>();
                        List<int> lstRowError_MonHoc_KhongCoKiTu = new List<int>();
                        List<int> lstRowError_TenMonHocTienQuyet_KhongCoKiTu = new List<int>();

                        for (int rowIterator = 2; rowIterator <= noOfRow; rowIterator++)
                        {
                            var lsthocphantienquyet = new HocPhanTienQuyetDTO();
                            lsthocphantienquyet.IDMonHoc = Convert.ToInt32(workSheet.Cells[rowIterator, 1].Value);
                            lsthocphantienquyet.IDMonHocTienQuyet = Convert.ToInt32(workSheet.Cells[rowIterator, 2].Value);
                            lsthocphantienquyet.GhiChu = Convert.ToString(workSheet.Cells[rowIterator, 3].Value).Trim();

                            var findmonhoc = CheckLoiMonHocTienQuyetTheoMonHocDaTonTai(lsthocphantienquyet.IDMonHoc, lsthocphantienquyet.IDMonHocTienQuyet);
                            if(lsthocphantienquyet.IDMonHoc < 1)
                            {
                                lstRowError_MonHoc_KhongCoKiTu.Add(rowIterator);

                            }
                            if(lsthocphantienquyet.IDMonHocTienQuyet < 1)
                            {
                                lstRowError_TenMonHocTienQuyet_KhongCoKiTu.Add(rowIterator);

                            }
                            if (findmonhoc > 0)
                            {
                                lstRowError_TenMonHocTienQuyet_Trung.Add(rowIterator);

                            }
                            else
                            {
                                hocphantienquyetList.Add(lsthocphantienquyet);
                            }
                        }

                        if(lstRowError_MonHoc_KhongCoKiTu.Count() > 0 || lstRowError_TenMonHocTienQuyet_KhongCoKiTu.Count() > 0 || lstRowError_TenMonHocTienQuyet_Trung.Count() > 0)
                        {
                            if (lstRowError_MonHoc_KhongCoKiTu.Count() > 0)
                            {
                                var error = "Các dòng chưa nhập đầy đủ thông tin trong File Excel cột Tên Môn Học : ";
                                foreach (var item in lstRowError_MonHoc_KhongCoKiTu)
                                {
                                    error += "Dòng " + item + " ";
                                }
                                ViewBag.Errorkhongcokitu += error + "</br>";
                            }
                            if (lstRowError_TenMonHocTienQuyet_KhongCoKiTu.Count() > 0)
                            {
                                var error = "Các dòng chưa nhập đầy đủ thông tin trong File Excel cột Tên Môn Học Tiên Quyết : ";
                                foreach (var item in lstRowError_TenMonHocTienQuyet_KhongCoKiTu)
                                {
                                    error += "Dòng " + item + " ";
                                }
                                ViewBag.Errorkhongcokitu += error + "</br>";
                            }
                            if (lstRowError_TenMonHocTienQuyet_Trung.Count() > 0)
                            {
                                var error = "Các dòng bị trùng ở cột Tên Môn Học Tiên Quyết trong File Excel : ";
                                foreach (var item in lstRowError_TenMonHocTienQuyet_Trung)
                                {
                                    error += "Dòng " + item + " ";
                                }
                                ViewBag.trungdata += error + "</br>";
                            }
                            var lsthocphanTQs = LayDanhSachHocPhanTienQuyet();
                            ViewBag.monhoc = LayDanhSachMonHoc();
                            ViewBag.monhoctienquyet = LayDanhSachMonHoc();
                            return View("Index", lsthocphanTQs);
                        }
                        else
                        {
                            foreach (var item in hocphantienquyetList)
                            {
                                ThemHocPhanTienQuyet(item);
                            }
                        }
                    }
                }
                else
                {
                    ViewBag.Error = "Chưa có File";
                    var lsthocphanTQs = LayDanhSachHocPhanTienQuyet();
                    ViewBag.monhoc = LayDanhSachMonHoc();
                    ViewBag.monhoctienquyet = LayDanhSachMonHoc();
                    return View("Index", lsthocphanTQs);
                }
            }
            ViewBag.Success = "Thành Công";
            var lsthocphanTQ = LayDanhSachHocPhanTienQuyet();
            ViewBag.monhoc = LayDanhSachMonHoc();
            ViewBag.monhoctienquyet = LayDanhSachMonHoc();
            return View("Index", lsthocphanTQ);
        }

        public int CheckLoiMonHocTienQuyetTheoMonHocDaTonTai(int? idMonHoc,int? idMonHocTienQuyet)
        {
            using(MonHocBusiness bs = new MonHocBusiness())
            {
                return bs.CheckLoiMonHocTienQuyetTheoMonHocDaTonTai(idMonHoc, idMonHocTienQuyet);
            }
        }

        public List<MonHocDTO> LayDanhSachMonHocTienQuyet(int id)
        {
            using(MonHocBusiness bs = new MonHocBusiness())
            {
                return bs.LayDanhSachMonHocTienQuyet(id);
            }
        }

        public int LayHocPhanTienQuyetDaTonTai(int? id)
        {
            using (HocPhanTienQuyetBusiness bs = new HocPhanTienQuyetBusiness())
            {
                return bs.LayHocPhanTienQuyetDaTonTai(id);
            }
        }

Demo_Login2/Areas/AdminPage/Views/HocPhanTienQuyet/Create.cshtml
@model Demo_Login2.Models.DTO.HocPhanTienQuyetDTO
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Tạo Học Phần Tiên Quyết</h1>
                    <br />
                    <button class="btn btn-outline-warning" onclick="location.href='@Url.Action("Index", "HocPhanTienQuyet")'">
                        <i class="fas fa-arrow-left"></i>
                        Quay về
                    </button>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Tạo Học Phần Tiên Quyết</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        @using (Html.BeginForm("Create","HocPhanTienQuyet"))
        {
            @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.IDMonHoc, "Tên Môn Học", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.IDMonHoc, @ViewData["monhoc"] as SelectList, htmlAttributes: new { @class = "form-control" ,@id = "idMonHoc"})
                    @Html.ValidationMessageFor(model => model.IDMonHoc, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.IDMonHocTienQuyet, "Tên Môn Học Tiên Quyết", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.IDMonHocTienQuyet, @ViewData["monhoctienquyet"] as SelectList, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IDMonHocTienQuyet, "", new { @class = "text-danger" })
                </div>
            </div>
            <p class="text-danger">@ViewBag.Error</p>

            <div class="form-group">
                @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.GhiChu, new { cols = 60, rows = 10, @class = "form-control", placeholder = "Nhập Ghi Chú" })
                    @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
            <div class="form-group">
                <button class="btn btn-outline-success">
                    <i class="fas fa-check"></i>
                    Lưu
                </button>
            </div>
        }
    </section>
</div>
<script src="~/Content/plugins/jquery/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#idMonHoc").change(function () {
            var idMonHoc = $('#idMonHoc').val();


            document.cookie = "idMonHoc=" + idMonHoc;

            var link = '@Url.Action("Create_ThayDoiMonHoc", "HocPhanTienQuyet", new { id = "_id_" })';
            link = link.replace("_id_", idMonHoc);
            location.pathname = link;
        });
    })
</script>

Demo_Login2/Areas/AdminPage/Views/HocPhanTienQuyet/Details.cshtml
@model Demo_Login2.Models.DTO.HocPhanTienQuyetDTO
@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Chi Tiết Học Phần Tiên Quyết</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                            <li class="breadcrumb-item active">Chi Tiết Học Phần Tiên Quyết</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <section class="content">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.IDMonHoc, "Tên Môn Học", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @foreach (var row in ViewBag.monhoc)
                        {
                            if (row.ID == Model.IDMonHoc)
                            {
                                <p>@row.TenMonHoc</p>
                            }
                        }
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.IDMonHocTienQuyet, "Tên Môn Học Tiên Quyết", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @foreach (var row in ViewBag.monhoctienquyet)
                        {
                            if (row.ID == Model.IDMonHocTienQuyet)
                            {
                                <p>@row.TenMonHoc</p>
                            }
                        }
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DisplayFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })

                    </div>
                </div>
            </div>

            }
        </section>
        <br />
        <button class="btn btn-outline-warning" onclick="location.href='@Url.Action("Index", "HocPhanTienQuyet")'">
            <i class="fas fa-arrow-left"></i>
            Quay về
        </button>
    </div>

Demo_Login2/Areas/AdminPage/Views/HocPhanTienQuyet/Edit.cshtml
@model Demo_Login2.Models.DTO.HocPhanTienQuyetDTO
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Sửa Học Phần Tiên Quyết</h1>
                    <br />
                    <button class="btn btn-outline-warning" onclick="location.href='@Url.Action("Index", "HocPhanTienQuyet")'">
                        <i class="fas fa-arrow-left"></i>
                        Quay về
                    </button>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Sửa Học Phần Tiên Quyết</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        @using (Html.BeginForm("Edit", "HocPhanTienQuyet", new { id = Request.Cookies["idEdit"].Value }))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.IDMonHoc, "Tên Môn Học", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.IDMonHoc, @ViewData["monhoc"] as SelectList, htmlAttributes: new { @class = "form-control", @id = "idMonHoc" })
                        @Html.ValidationMessageFor(model => model.IDMonHoc, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.IDMonHocTienQuyet, "Tên Môn Học Tiên Quyết", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.IDMonHocTienQuyet, @ViewData["monhoctienquyet"] as SelectList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IDMonHocTienQuyet, "", new { @class = "text-danger" })
                    </div>
                </div>
                <p class="text-danger">@ViewBag.Error</p>
                <div class="form-group">
                    @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.GhiChu, new { cols = 60, rows = 10, @class = "form-control", placeholder = "Nhập Ghi Chú" })
                        @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <button class="btn btn-outline-success">
                    <i class="fas fa-check"></i>
                    Lưu
                </button>
            </div>
        }
    </section>
</div>

<script src="~/Content/plugins/jquery/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#idMonHoc").change(function () {
            var idMonHoc = $('#idMonHoc').val();


            document.cookie = "idMonHoc=" + idMonHoc;

            var link = '@Url.Action("Edit_ThayDoiMonHoc", "HocPhanTienQuyet", new { id = "_id_" })';
            link = link.replace("_id_", idMonHoc);
            location.pathname = link;
        });
    })
</script>

Demo_Login2/Areas/AdminPage/Views/HocPhanTienQuyet/Index.cshtml
@model List<Demo_Login2.Models.DTO.HocPhanTienQuyetDTO>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Học Phần Tiên Quyết</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "ThongKe")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Học Phần Tiên Quyết</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        <div class="card">
            <div class="card-header">
                <button class="btn btn-outline-primary" title="Thêm" style="cursor:pointer" onclick="location.href='@Url.Action("Create","HocPhanTienQuyet")'">
                    <i class="fas fa-plus">
                        Thêm
                    </i>
                </button>

                <button class="btn btn-outline-success" title="Upload file" style="cursor:pointer" data-toggle="modal" data-target="#exampleModal">
                    <i class="fas fa-upload">
                        Upload file
                    </i>
                </button>

                @using (Html.BeginForm("Upload", "HocPhanTienQuyet", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <br />
                    @Html.AntiForgeryToken()
                    <div id="exampleModal" class="modal" tabindex="-1" role="dialog">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    Upload file
                                </div>
                                <div class="modal-body">
                                    <input type="file" name="UploadedFile" />
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-primary">Lưu</button>
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                                </div>
                            </div>
                        </div>
                    </div>

                }
                <p class="text-danger">@ViewBag.Error</p>
                <p class="text-danger">@Html.Raw(ViewBag.trungdata)</p>
                <p class="text-danger">@Html.Raw(ViewBag.Errorkhongcokitu)</p>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Môn Học</th>
                            <th>Tên Môn Học Tiên Quyết</th>
                            @*<th>Ghi Chú</th>*@
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            <tr>
                                @foreach (var row in ViewBag.monhoc)
                                {
                                    if (row.ID == item.IDMonHoc)
                                    {
                                        <td>@row.TenMonHoc</td>
                                    }
                                }
                                @foreach (var row in ViewBag.monhoctienquyet)
                                {
                                    if (row.ID == item.IDMonHocTienQuyet)
                                    {
                                        <td>@row.TenMonHoc</td>
                                    }
                                }

                                @*<td>@item.GhiChu</td>*@
                                <td>
                                    <button class="btn btn-outline-warning" title="Sửa" style="cursor:pointer" onclick="location.href='@Url.Action("Edit","HocPhanTienQuyet",new {id = item.ID})'">
                                        <i class="fas fa-pen"></i>
                                        Sửa
                                    </button>
                                    <button class="btn btn-outline-danger btndeleteHocPhanTienQuyet" title="Xóa" style="cursor:pointer" data-id="@item.ID">
                                        <i class="fas fa-trash"></i>
                                        Xóa
                                    </button>
                                    <button class="btn btn-outline-info" title="Xem chi tiết" style="cursor:pointer" onclick="location.href='@Url.Action("Details","HocPhanTienQuyet",new {id = item.ID})'">
                                        <i class="fas fa-file-invoice"></i>
                                        Xem chi tiết
                                    </button>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </section>
</div>

<!--Error Delete-->
@if (TempData["error"] != null)
{
    <script>
        window.onload = function () {
            swal({
                title: "Xoá không thành công do học phần tiên quyết đang sử dụng dịch vụ khác",
                text: "",
                icon: "warning",
            })
        }
    </script>
}<!--Warning Error Upload File Excel-->
@if (ViewBag.Success != null)
{
    <script>
        window.onload = function () {
            swal({
                title: "Thành công",
                text: "",
                icon: "success",
            })
        }
    </script>
}

@if (ViewBag.trungdata != null)
{
    <script>
        window.onload = function () {
            swal({
                title: "Môn Học Tiên Quyết đã trong Môn Học này",
                text: "",
                icon: "warning",
            })
        }
    </script>
}

@if (ViewBag.Errorkhongcokitu != null)
{
    <script>
        window.onload = function () {
            swal({
                title: "Lỗi không có kí tự",
                text: "",
                icon: "warning",
            })
        }
    </script>
}

<script src="~/Content/plugins/jquery/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#btnShowModal_Add").click(function () {
            $("#AddModal").modal('show');
        });

        $("#btnHideModal_Add").click(function () {
            $("#AddModal").modal('hide');
        });

        $(".btndeleteHocPhanTienQuyet").click(function () {
            var dataId = $(this).attr("data-id");
            swal({
                title: "Xác nhận?",
                text: "Bạn có chắc muốn xóa!!!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        window.location = "@Url.Action("Delete", "HocPhanTienQuyet")/" + dataId;

                        swal("Xóa thành công", {
                            icon: "success",
                        });
                    }
                });
        });

    });
</script>