Demo_Login2/Areas/GiangVienPage/Controllers/KetQuaLapKeHoachDangKiSinhVienTheoLopChuNhiemController.cs
using Demo_Login2.Areas.AdminPage.Business;
using Demo_Login2.Models.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Demo_Login2.Areas.GiangVienPage.Controllers
{
    public class KetQuaLapKeHoachDangKiSinhVienTheoLopChuNhiemController : Controller
    {
        // GET: GiangVienPage/KetQuaLapKeHoachDangKiSinhVienTheoLopChuNhiem
        public ActionResult Index()
        {
            HttpCookie idlop = HttpContext.Request.Cookies.Get("idLopChuNhiem");
            var idLopChuNhiem = 0;
            List<HocKiDTO> lsthocki = new List<HocKiDTO>();
            if (String.IsNullOrEmpty(idlop.Value))
            {
                // bao loi
                ViewBag.ErrorChuNhiem = "Lỗi Giảng Viên chưa là Chủ Nhiệm";
            }else
            {
                idLopChuNhiem = Convert.ToInt32(idlop.Value); 
                lsthocki = LayDanhSachHocKi();
            }


            var lstketqua = this.LayDanhSachKetQuaLapKeHoachDangKiSinhVien_TheoLopChuNhiem(idLopChuNhiem, 0, 0);
            var lstlophoc = LayDanhSachLopHocTheoID(idLopChuNhiem);
            var lstsinhvien = LayDanhSachSinhVienTheoLopChuNhiem(idLopChuNhiem);

            lsthocki.Insert(0, new HocKiDTO
            {
                ID = 0,
                TenHocKi = "Chọn Học Kì"
            });

            lstsinhvien.Insert(0, new AccountDTO
            {
                ID = 0,
                Ma = "Chọn Mã Sinh Viên"
            });
            //lstlophoc.Insert(0, new LopHocDTO
            //{
            //    ID = 0,
            //    TenLop = "Chọn Lớp Học"
            //});

            ViewData["LopHoc"] = new SelectList(lstlophoc, "ID", "TenLop");
            ViewData["HK"] = new SelectList(lsthocki, "ID", "TenHocKi");
            ViewData["SV"] = new SelectList(lstsinhvien, "ID", "Ma");

            Session["lstketquakehoach"] = lstketqua;
            Session["idHocKi"] = 0;

            ViewBag.HocKi = LayDanhSachHocKi();
            ViewBag.SinhVien = LayDanhSachSinhVienTheoLopChuNhiem(idLopChuNhiem);
            return View(lstketqua);
        }

        [HttpPost]
        public ActionResult Index(int idLopHoc,int idHocKi,int idSinhVien)
        {

            var lstketqua = this.LayDanhSachKetQuaLapKeHoachDangKiSinhVien_TheoLopChuNhiem(idLopHoc, idHocKi, idSinhVien);
            var lstlophoc = LayDanhSachLopHocTheoID(idLopHoc);
            var lsthocki = LayDanhSachHocKi();
            var lstsinhvien = LayDanhSachSinhVienTheoLopChuNhiem(idLopHoc);

            lsthocki.Insert(0, new HocKiDTO
            {
                ID = 0,
                TenHocKi = "Chọn Học Kì"
            });
            lstsinhvien.Insert(0, new AccountDTO
            {
                ID = 0,
                Ma = "Chọn Mã Sinh Viên"
            });

            ViewData["LopHoc"] = new SelectList(lstlophoc, "ID", "TenLop");
            ViewData["HK"] = new SelectList(lsthocki, "ID", "TenHocKi");
            ViewData["SV"] = new SelectList(lstsinhvien, "ID", "Ma");

            Session["lstketquakehoach"] = lstketqua;
            Session["idHocKi"] = 0;

            ViewBag.HocKi = LayDanhSachHocKi();
            ViewBag.SinhVien = LayDanhSachSinhVienTheoLopChuNhiem(idLopHoc);

            return View(lstketqua);
        }

        public List<SinhVienDangKiKeHoachHocTapDTO> LayDanhSachKetQuaLapKeHoachDangKiSinhVien_TheoLopChuNhiem(int idLopHoc,int idHocKi,int idSinhVien)
        {
            using(KetQuaLapKeHoachDangKiSinhVienBusiness bs = new KetQuaLapKeHoachDangKiSinhVienBusiness())
            {
                return bs.LayDanhSachKetQuaLapKeHoachDangKiSinhVien_TheoLopChuNhiem(idLopHoc,idHocKi,idSinhVien);
            }
        }

        public List<LopHocDTO> LayDanhSachLopHocTheoID(int idLopHoc)
        {
            using(LopHocBusiness bs = new LopHocBusiness())
            {
                return bs.LayDanhSachLopHocTheoID(idLopHoc);
            }
        }

        public List<HocKiDTO> LayDanhSachHocKi()
        {
            using (HocKiBusiness bs = new HocKiBusiness())
            {
                return bs.LayDanhSachHocKi();
            }
        }

        public List<AccountDTO> LayDanhSachSinhVienTheoLopChuNhiem(int idLopHoc)
        {
            using(TaiKhoanBusiness bs = new TaiKhoanBusiness())
            {
                return bs.LayDanhSachSinhVienTheoLopChuNhiem(idLopHoc);
            }
        }
    }
}

Demo_Login2/Areas/GiangVienPage/Views/KetQuaLapKeHoachDangKiSinhVienTheoLopChuNhiem/Index.cshtml
@model List<Demo_Login2.Models.DTO.SinhVienDangKiKeHoachHocTapDTO>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/AdminPage/Views/Shared/_AdminLayout.cshtml";
}

<style>
    .tbl-head {
        text-align: center;
        background: #FECE7A;
        border: #fff solid 1px;
        text-transform: uppercase;
    }

    .col-400px {
        width: 400px;
    }

    .custom-label {
        border: none;
    }

        .custom-label:focus {
            outline: none;
        }

    .col-120 {
        width: 120px;
        text-align: center;
    }

    .col-400 {
        width: 400px;
    }

    .col-55 {
        width: 55px;
        text-align: center;
    }

    .col-63 {
        width: 63px;
        text-align: center;
    }
    /*.col-350{
        width:400px
    }*/
    .col-350 {
        text-align: center;
        width: 350px;
    }

    .col-220 {
        text-align: center;
        width: 220px;
    }

    .center {
        text-align: center;
    }
</style>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Kết Quả Lập Kế Hoạch Học Tập</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "ChuongTrinhDaoTao")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Kết Quả Lập Kế Hoạch Học Tập</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <section class="content">
        <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
                @using (Html.BeginForm("Index", "KetQuaLapKeHoachDangKiSinhVienTheoLopChuNhiem", FormMethod.Post))
                {
                    <br />
                    <div class="form-group row">
                        <div class="col-sm-2" style="margin: 0 auto; min-width: 478px; display: flex; justify-content: center; align-items: center; ">
                            <label style="margin-right: 15px; margin-bottom: 0; font-size: 19px; width: 200px; ">Lớp Học</label>
                            @Html.DropDownList("idLopHoc", ViewData["LopHoc"] as SelectList, new { @class = "form-control"})
                        </div>
                        <div class="col-sm-2" style="margin: 0 auto; min-width: 478px; display: flex; justify-content: center; align-items: center; ">
                            <label style="margin-right: 15px; margin-bottom: 0; font-size: 19px; width: 200px; ">Học Kì</label>
                            @Html.DropDownList("idHocKi", ViewData["HK"] as SelectList, new { @class = "form-control" })
                        </div>
                        <div class="col-sm-2" style="margin: 0 auto; min-width: 478px; display: flex; justify-content: center; align-items: center; ">
                            <label style="margin-right: 15px; margin-bottom: 0; font-size: 19px; width: 200px; ">Mã Sinh Viên</label>
                            @Html.DropDownList("idSinhVien", ViewData["SV"] as SelectList, new { @class = "form-control" })
                        </div>
                        <div class="col-1" style="margin: 0 auto;display: flex; justify-content: center; align-items: center;">
                            <button type="submit" class="btn btn-outline-primary">Tìm</button>
                        </div>
                    </div>
                }
                <p class="text-danger">@ViewBag.Error</p>
                <table class="table table-bordered">
                    <tr class="tbl-head">
                        <th rowspan="2">TT</th>
                        <th rowspan="2">Mã học phần</th>
                        <th rowspan="2">Tên học phần</th>
                        <th rowspan="2">Số TC</th>
                        <th colspan="2">Số Tiết</th>
                        <th rowspan="2">Học Phần Tiên Quyết</th>
                        <th rowspan="2">Học Phần Học Trước</th>
                        <th rowspan="2">Khoa/Bộ môn</th>
                        <th rowspan="2">Đăng kí</th>
                    </tr>
                    <tr class="tbl-head">
                        <th colspan="1">LT</th>
                        <th colspan="1">TH</th>
                    </tr>

                    @{
                        foreach (var sinhvien in ViewBag.SinhVien)
                        {
                            var sv = Model.Where(s => s.IDAccount == sinhvien.ID);
                            if (sv.Count() > 0)
                            {
                                <tr>
                                    <th colspan="10">Mã Sinh Viên : @sinhvien.Ma</th>
                                </tr>
                                <tr>
                                    <th colspan="10">Họ Tên Sinh Viên : @sinhvien.HoVaTen</th>
                                </tr>
                            }
                            foreach (var hocki in ViewBag.hocki)
                            {
                                var stt = 0;
                                var TongTC_chuongtrinhdaotao_batbuoc = 0;
                                var TongTC_chuongtrinhdaotao_tuchon = 0;
                                var TongTC_ketquahoctap = 0;
                                var TongTC_monhocvuot = 0;

                                var chuongtrinhdaotao_batbuoc = Model.Where(c => c.IDPhanLoaiMonHoc == 1 && c.IDHocKi == hocki.ID && c.IDAccount == sinhvien.ID);
                                var chuongtrinhdaotao_tuchon = Model.Where(c => c.IDPhanLoaiMonHoc == 2 && c.IDHocKi == hocki.ID && c.IDAccount == sinhvien.ID);


                                if (chuongtrinhdaotao_batbuoc.Count() > 0 || chuongtrinhdaotao_tuchon.Count() > 0)
                                {
                                    <tr>
                                        <th colspan="10">@hocki.TenHocKi</th>
                                    </tr>
                                }
                                //Mon hoc bat buoc
                                if (chuongtrinhdaotao_batbuoc.Count() > 0)
                                {
                                    <tr>
                                        <th colspan="10">Bắt buộc</th>
                                    </tr>
                                    for (var i = 0; i < Model.Count(); i++)
                                    {
                                        if (@Model[i].IDPhanLoaiMonHoc == 1 && Model[i].IDHocKi == hocki.ID && Model[i].IDAccount == sinhvien.ID)
                                        {
                                            stt = stt + 1;
                                            <tr>
                                                <td class="center">@stt</td>
                                                <td class="col-120">@Model[i].MaMonHoc</td>
                                                <td class="col-400px">@Model[i].TenMonHoc</td>
                                                <td class="col-55">@Model[i].SoTinChi</td>
                                                <td class="col-63">@Model[i].SoTietLyThuyet</td>
                                                <td class="col-63">@Model[i].SoTietThucHanh</td>
                                                <td class="center">@Model[i].TenMonHocTienQuyet</td>
                                                <td class="center">@Model[i].TenMonHocHocTruoc</td>
                                                <td class="col-220">@Model[i].TenKhoaBoMon</td>

                                                @if (@Model[i].TrangThai == true)
                                                {
                                                    <td class="center col-120"><i class="fas fa-check text-success font-weight-bold" title="Đã Đăng Kí" style="cursor:pointer"></i></td>
                                                }
                                                else
                                                {
                                                    <td class="center col-120"><i class="fas fa-times text-danger font-weight-bold" title="Chưa Đăng Kí" style="cursor:pointer"></i></td>
                                                }
                                            </tr>
                                            TongTC_chuongtrinhdaotao_batbuoc = TongTC_chuongtrinhdaotao_batbuoc + Model[i].SoTinChi;
                                        }
                                    }
                                    if (TongTC_chuongtrinhdaotao_batbuoc > 0)
                                    {
                                        <tr>
                                            <td colspan="3" class="text-right font-weight-bold">Cộng học phần Bắt buộc</td>
                                            <td class="font-weight-bold center">@TongTC_chuongtrinhdaotao_batbuoc</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                    }
                                }
                                //Mon hoc tu chon
                                if (chuongtrinhdaotao_tuchon.Count() > 0)
                                {
                                    <tr>
                                        <th colspan="10">Tự chọn</th>
                                    </tr>
                                    for (var i = 0; i < Model.Count(); i++)
                                    {
                                        if (Model[i].IDPhanLoaiMonHoc == 2 && Model[i].IDHocKi == hocki.ID && Model[i].IDAccount == sinhvien.ID)
                                        {
                                            stt = stt + 1;
                                            <tr>
                                                <td class="center">@stt</td>
                                                <td class="col-120">@Model[i].MaMonHoc</td>
                                                <td class="col-400px">@Model[i].TenMonHoc</td>
                                                <td class="col-55">@Model[i].SoTinChi</td>
                                                <td class="col-63">@Model[i].SoTietLyThuyet</td>
                                                <td class="col-63">@Model[i].SoTietThucHanh</td>
                                                <td class="center">@Model[i].TenMonHocTienQuyet</td>
                                                <td class="center">@Model[i].TenMonHocHocTruoc</td>
                                                <td class="col-220">@Model[i].TenKhoaBoMon</td>

                                                @if (@Model[i].TrangThai == true)
                                                {
                                                    <td class="center col-120"><i class="fas fa-check text-success font-weight-bold" title="Đã Đăng Kí" style="cursor:pointer"></i></td>
                                                }
                                                else
                                                {
                                                    <td class="center col-120"><i class="fas fa-times text-danger font-weight-bold" title="Chưa Đăng Kí" style="cursor:pointer"></i></td>
                                                }
                                            </tr>
                                            TongTC_chuongtrinhdaotao_tuchon = TongTC_chuongtrinhdaotao_tuchon + Model[i].SoTinChi;
                                        }
                                    }
                                    if (TongTC_chuongtrinhdaotao_tuchon > 0)
                                    {
                                        <tr>
                                            <td colspan="3" class="text-right font-weight-bold">Cộng học phần Tự chọn</td>
                                            <td class="font-weight-bold center">@TongTC_chuongtrinhdaotao_tuchon</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                    }
                                }
                            }
                        }

                    }

                </table>



            </div>
        </div>
    </section>
</div>
@if (ViewBag.ErrorChuNhiem != null)
{
    <script>
        window.onload = function () {
            swal({
                title: "Lỗi Giảng Viên chưa là Chủ Nhiệm",
                text: "",
                icon: "warning",
            })
        }
    </script>
}